# Generated by Django 4.1.13 on 2024-05-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_profile', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_profile', models.CharField(max_length=255, null=True)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_collection', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miscellaneous_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_profile', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'On going')], max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('business_profile', models.CharField(max_length=255, null=True)),
                ('business_profile_id', models.IntegerField(null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_no', models.CharField(max_length=20, unique=True)),
                ('passport_expiration_date', models.DateField(null=True)),
                ('emirates_id', models.CharField(max_length=20, unique=True)),
                ('id_expiration_date', models.DateField()),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transportation_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('joining_date', models.DateField()),
                ('job_role', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_profile', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_profile', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_profile', models.CharField(max_length=255, null=True)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_profile', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='employee_passport_expiration_reminder_days',
            field=models.PositiveIntegerField(null=True, verbose_name='Employee Passport Expiration Reminder (days)'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='employee_visa_expiration_reminder_days',
            field=models.PositiveIntegerField(null=True, verbose_name='Employee Visa Expiration Reminder (days)'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='vat_submission_date_reminder_days',
            field=models.PositiveIntegerField(null=True, verbose_name='VAT Submission Date Reminder (days)'),
        ),
        migrations.CreateModel(
            name='MiscellaneousIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cheque_date', models.DateField()),
                ('cheque_no', models.CharField(max_length=255)),
                ('business_profile', models.CharField(max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.bank')),
                ('mode_of_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.transactionmode')),
                ('receipt_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.receipttype')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cheque_date', models.DateField()),
                ('cheque_no', models.CharField(max_length=255)),
                ('business_profile', models.CharField(max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.bank')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.customer')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.transactionmode')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_start_time', models.TimeField(blank=True, null=True)),
                ('business_end_time', models.TimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('business_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BankSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cheque_date', models.DateField()),
                ('cheque_no', models.CharField(max_length=255)),
                ('business_profile', models.CharField(max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.bank')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.customer')),
                ('mode_of_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.transactionmode')),
            ],
        ),
    ]
