# Generated by Django 5.0.6 on 2024-05-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='employee_passport_expiration_reminder_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Employee Passport Expiration Reminder (days)'),
            preserve_default=False,
        ),
    ]
