# Generated by Django 5.0.6 on 2024-05-21 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0002_businessprofile_employee_passport_expiration_reminder_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.shop'),
            preserve_default=False,
        ),
    ]
