# Generated by Django 5.0.6 on 2024-05-21 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0003_businessprofile_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_no', models.CharField(max_length=20, unique=True)),
                ('passport_expiration_date', models.DateField()),
                ('emirates_id', models.CharField(max_length=20, unique=True)),
                ('id_expiration_date', models.DateField()),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transportation_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('joining_date', models.DateField()),
                ('job_role', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.businessprofile')),
            ],
        ),
    ]
