# Generated by Django 4.1.13 on 2024-05-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0003_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_outstanding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cheque_date', models.DateField()),
                ('cheque_no', models.CharField(max_length=255)),
                ('business_profile', models.CharField(max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.bank')),
                ('mode_of_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.transactionmode')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.supplier')),
            ],
        ),
    ]
