# Generated by Django 4.1.13 on 2024-05-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0004_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
