# Generated by Django 4.1.13 on 2024-05-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0005_expense_bankdeposits'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='card_sale',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='cash_sale',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='credit_sale',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
