# Generated by Django 5.0.6 on 2024-05-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0006_bank_customer_dailysummary_expensetype_receipttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='business_profile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='business_profile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='business_profile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='business_profile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='business_profile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receipttype',
            name='business_profile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='business_profile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmode',
            name='business_profile',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
