# Generated by Django 4.1.13 on 2024-05-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0006_dailysummary_card_sale_dailysummary_cash_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposits',
            name='daily_summary_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banksales',
            name='daily_summary_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creditcollection',
            name='daily_summary_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='daily_summary_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='daily_summary_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miscellaneousincome',
            name='daily_summary_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='daily_summary_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayments',
            name='daily_summary_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmode',
            name='name',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('credit', 'Credit')], max_length=255),
        ),
    ]
