# Generated by Django 5.0.6 on 2024-05-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0007_alter_bank_business_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
