# Generated by Django 5.0.6 on 2024-05-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0008_customer_status_supplier_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='shop',
        ),
    ]
