# Generated by Django 4.1.13 on 2024-05-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0008_alter_businesstiming_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='business_end_time',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='business_start_time',
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
