# Generated by Django 5.0.6 on 2024-05-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0009_remove_businessprofile_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receipttype',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transactionmode',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
