# Generated by Django 4.1.13 on 2024-05-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0009_remove_businessprofile_business_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='update_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
