# Generated by Django 4.1.13 on 2024-05-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0010_bank_update_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmode',
            name='name',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('bank transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('credit', 'Credit')], max_length=255),
        ),
    ]
