# Generated by Django 5.0.6 on 2024-05-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0010_bank_status_businessprofile_status_employee_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='status',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='expensetype',
            name='status',
        ),
        migrations.RemoveField(
            model_name='receipttype',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transactionmode',
            name='status',
        ),
    ]
