# Generated by Django 4.1.13 on 2024-05-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0011_alter_transactionmode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='opening_balance',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
