# Generated by Django 5.0.6 on 2024-05-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0011_remove_bank_status_remove_businessprofile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='business_profile_id',
            field=models.IntegerField(null=True),
        ),
    ]
