# Generated by Django 4.1.13 on 2024-05-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0013_banksale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cheque_date', models.DateField()),
                ('cheque_no', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.bank')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.customer')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.transactionmode')),
            ],
        ),
    ]
