# Generated by Django 4.1.13 on 2024-05-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0014_creditcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipttype',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionmode',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
