# Generated by Django 4.1.13 on 2024-05-31 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0014_alter_bankdeposits_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposits',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.customer'),
        ),
    ]
