# Generated by Django 4.1.13 on 2024-05-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0015_bank_status_employee_status_expensetype_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banksale',
            name='business_profile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditcollection',
            name='business_profile',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
