# Generated by Django 4.1.13 on 2024-06-04 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0016_remove_bankdeposits_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(max_length=254)),
                ('email_3', models.EmailField(max_length=254)),
                ('mobile_1', models.CharField(max_length=20)),
                ('mobile_2', models.CharField(max_length=20)),
                ('mobile_3', models.CharField(max_length=20)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.businessprofile')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
