# Generated by Django 4.1.13 on 2024-05-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0016_banksale_business_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banksale',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
