# Generated by Django 4.1.13 on 2024-05-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0017_alter_banksale_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banksale',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
