# Generated by Django 4.1.13 on 2024-06-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0017_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposits',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankdeposits',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankdeposits',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banksales',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banksales',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='creditcollection',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditcollection',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='miscellaneousincome',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='miscellaneousincome',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplierpayments',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierpayments',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
