# Generated by Django 4.1.13 on 2024-05-23 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0018_alter_banksale_created_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankSale',
            new_name='BankSales',
        ),
    ]
