# Generated by Django 4.1.13 on 2024-05-24 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0019_rename_banksale_banksales'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscellaneousIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cheque_date', models.DateField()),
                ('cheque_no', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.bank')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.businessprofile')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.expensetype')),
                ('mode_of_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.transactionmode')),
            ],
        ),
    ]
