# Generated by Django 4.1.13 on 2024-06-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0019_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
