# Generated by Django 4.1.13 on 2024-05-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0020_miscellaneousincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscellaneousincome',
            name='business_profile',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
