# Generated by Django 4.1.13 on 2024-06-06 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0021_alter_bankdeposits_bank_alter_banksales_bank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FAB', 'FAB'), ('ADCB', 'ADCB'), ('AL MASRAF', 'AL MASRAF'), ('CBOD', 'CBOD'), ('Emirates NBD', 'Emirates NBD'), ('Mashreq', 'Mashreq'), ('Bank of Sharjah', 'Bank of Sharjah'), ('United Arab Bank', 'United Arab Bank'), ('Invest Bank', 'Invest Bank'), ('Rak Bank', 'Rak Bank'), ('CBI', 'CBI'), ('NBF', 'NBF'), ('NBQ', 'NBQ'), ('Dubai Islamic Bank', 'Dubai Islamic Bank'), ('Emirates Islamic Bank', 'Emirates Islamic Bank'), ('Sharjah Islamic Bank', 'Sharjah Islamic Bank'), ('ADIB', 'ADIB'), ('Al Hilal Bank', 'Al Hilal Bank'), ('Ajman Bank', 'Ajman Bank'), ('Arab Bank', 'Arab Bank'), ('Banque Misr', 'Banque Misr'), ('Bank of Baroda', 'Bank of Baroda'), ('Nilein Bank', 'Nilein Bank'), ('NBB', 'NBB'), ('BNP Paribas', 'BNP Paribas'), ('HSBC', 'HSBC'), ('AAIB', 'AAIB'), ('Al Khaliji', 'Al Khaliji'), ('ABK', 'ABK'), ('Barclays Bank', 'Barclays Bank'), ('HBL', 'HBL'), ('Habib Bank AG Zurich', 'Habib Bank AG Zurich'), ('Standard Chartered', 'Standard Chartered'), ('Citi Bank', 'Citi Bank'), ('Bank Saderat Iran', 'Bank Saderat Iran'), ('Bank Melli Iran', 'Bank Melli Iran'), ('Banque Banorient France', 'Banque Banorient France'), ('United Bank Limited', 'United Bank Limited'), ('Doha Bank', 'Doha Bank'), ('Samba Financial Group', 'Samba Financial Group'), ('Deutsche Bank', 'Deutsche Bank'), ('ICBC', 'ICBC'), ('NBK', 'NBK'), ('GIB', 'GIB'), ('Bank of China', 'Bank of China'), ('BOK', 'BOK'), ('Credit Agricole', 'Credit Agricole'), ('IDB', 'IDB')], max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='banksales',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.allbank'),
        ),
        migrations.AlterField(
            model_name='creditcollection',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.allbank'),
        ),
        migrations.AlterField(
            model_name='miscellaneousincome',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.allbank'),
        ),
    ]
