# Generated by Django 4.1.13 on 2024-06-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0025_alter_withdrawal_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbank',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
