# Generated by Django 4.1.13 on 2024-06-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0026_allbank_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllBank',
        ),
    ]
