# Generated by Django 4.1.13 on 2024-06-07 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0028_allbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposits',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.allbank'),
        ),
        migrations.AlterField(
            model_name='banksales',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.allbank'),
        ),
        migrations.AlterField(
            model_name='creditcollection',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.allbank'),
        ),
        migrations.AlterField(
            model_name='miscellaneousincome',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.allbank'),
        ),
    ]
