# Generated by Django 4.1.13 on 2024-06-07 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0029_alter_bankdeposits_bank_alter_banksales_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposits',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits_as_bank', to='biztrackapp.bank'),
        ),
        migrations.AlterField(
            model_name='banksales',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.bank'),
        ),
        migrations.AlterField(
            model_name='creditcollection',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.bank'),
        ),
        migrations.AlterField(
            model_name='miscellaneousincome',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.bank'),
        ),
    ]
