# Generated by Django 4.1.13 on 2024-06-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0032_alter_bankdeposits_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supplierpayments',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
