# Generated by Django 4.1.13 on 2024-06-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0034_expense_create_date_supplierpayments_create_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
