# Generated by Django 4.1.13 on 2024-06-14 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0036_remove_expense_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='name',
        ),
        migrations.AddField(
            model_name='bank',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biztrackapp.allbank'),
        ),
    ]
