# Generated by Django 5.0.6 on 2024-06-26 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0038_alter_allbank_created_on_alter_bank_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banksales',
            name='outstanding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='creditcollection',
            name='opening_outstanding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bank',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='receipttype',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transactionmode',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
