# Generated by Django 5.0.6 on 2024-07-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0039_banksales_outstanding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_on',
            field=models.DateField(null=True),
        ),
    ]
