# Generated by Django 4.1.13 on 2024-07-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0043_alter_user_is_admin_alter_user_is_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_on',
            field=models.DateField(null=True),
        ),
    ]
