# Generated by Django 4.1.13 on 2024-07-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0044_alter_expense_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
