# Generated by Django 5.0.6 on 2024-07-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0044_alter_creditcollection_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmode',
            name='transaction_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
