# Generated by Django 4.1.13 on 2024-07-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0045_alter_expense_created_on'),
        ('biztrackapp', '0046_dailysummaryremark'),
    ]

    operations = [
    ]
