# Generated by Django 4.1.13 on 2024-07-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biztrackapp', '0047_merge_20240719_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposits',
            name='created_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='banksales',
            name='created_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='creditcollection',
            name='created_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='created_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='miscellaneousincome',
            name='created_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='supplierpayments',
            name='created_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transactionmode',
            name='name',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('bank transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('credit', 'Credit'), ('free', 'Free')], max_length=255),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='created_on',
            field=models.DateField(null=True),
        ),
    ]
